working Hough-based tracking but needs further development to deal with scale limitation
Former-commit-id: 9225f4bf17a9d15a9e3953483ed838af46c8c9b6

diff --git a/aved-mbarivision/src/main/cpp/configure b/aved-mbarivision/src/main/cpp/configure
--- a/aved-mbarivision/src/main/cpp/configure
+++ b/aved-mbarivision/src/main/cpp/configure
@@ -601,6 +601,7 @@ PACKAGE_BUGREPORT=''
 ac_default_prefix=/usr/local/aved
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
+with_opencv
 with_xercesc
 with_saliency
 ac_ct_CXX
@@ -655,6 +656,7 @@ ac_user_opts='
 enable_option_checking
 with_saliency
 with_xercesc
+with_opencv
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1292,6 +1294,8 @@ Optional Packages:
   --with-xercesc=DIR      where the Xercesc is installed (e.g.,
                           $HOME/Xerces-C_2_7_0 )
                           [default=$HOME/Xerces-C_2_7_0]
+  --with-opencv=DIR       where the OpenCV is installed (e.g., /usr/local/ )
+                          [default=/usr/local/]
 
 Some influential environment variables:
   CC          C compiler command
@@ -3289,6 +3293,105 @@ $as_echo "$as_me: error: Xercesc directory \"$with_xercesc\" missing or incorrec
                     Set the correct path with --with-xercesc=DIR   " >&5
 $as_echo "$as_me: error: Xercesc directory $with_xercesc missing or incorrect.
                     Set the correct path with --with-xercesc=DIR   " >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+
+
+
+# Enable users to specify where OpenCV is installed.
+# Note the 2.4.9 version is required
+# The default is to have the libraries in the /usr/local/ directory
+
+# Check whether --with-opencv was given.
+if test "${with_opencv+set}" = set; then
+  withval=$with_opencv;
+else
+  with_opencv=/usr/local/
+fi
+
+
+# Use the supplied (or default) OpenCV directory to set
+# makefile variables
+if test -d "$with_opencv" ; then
+
+   opencv_cppflags_save="$CPPFLAGS"
+   opencv_ldflags_save="$LDFLAGS"
+   CPPFLAGS="$CPPFLAGS -I/usr/include -I$with_opencv"
+   LDFLAGS="$LDFLAGS -L$with_opencv/lib"
+
+   { $as_echo "$as_me:$LINENO: checking for libopencv_imgproc" >&5
+$as_echo_n "checking for libopencv_imgproc... " >&6; }
+	 libs_save=$LIBS
+	 LIBS="$LIBS -lopencv_imgproc -lopencv_imgproc "
+	 cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <opencv2/imgproc/imgproc.hpp>
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 $as_test_x conftest$ac_exeext
+       }; then
+  havelib_opencv=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	havelib_opencv=no
+fi
+
+rm -rf conftest.dSYM
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+	 LIBS=$libs_save
+	 if test "x$havelib_opencv" = xyes; then
+	    { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	    with_opencv=$with_opencv
+	 else
+	    { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+	    { { $as_echo "$as_me:$LINENO: error: OpenCV directory \"$with_opencv\" missing or incorrect.
+                        Set the correct path with --with-opencv=DIR" >&5
+$as_echo "$as_me: error: OpenCV directory \"$with_opencv\" missing or incorrect.
+                        Set the correct path with --with-opencv=DIR" >&2;}
+   { (exit 1); exit 1; }; }
+
+	 fi
+   else
+      { { $as_echo "$as_me:$LINENO: error: OpenCV directory $with_opencv missing or incorrect.
+                    Set the correct path with --with_opencv=DIR   " >&5
+$as_echo "$as_me: error: OpenCV directory $with_opencv missing or incorrect.
+                    Set the correct path with --with_opencv=DIR   " >&2;}
    { (exit 1); exit 1; }; }
    fi
 
