synced to moonjelly repository
Former-commit-id: 5805df8a5a0524b4f89f3cd9ac2989b27abdeedf

diff --git a/aved-mbarivision/src/main/scripts/cleanscratch b/aved-mbarivision/src/main/scripts/cleanscratch
--- a/aved-mbarivision/src/main/scripts/cleanscratch
+++ b/aved-mbarivision/src/main/scripts/cleanscratch
@@ -1,17 +1,16 @@
 #!/bin/bash
-#set -x
 #
 # Name: cleanscratch
 # This script clean up scratch space for a users
 
-# Copyright (c) MBARI 2007
+# Copyright (c) MBARI 2010
 # Author: D. Cline
-# Date: February 07, 2007
 #
-#
-#exit on error; this will exit this bash scrip when
-#any command exists with a non-zero exit code
-set -e
+# scripts are in
+# exit on error - this will exit this bash script when any command exits with
+# a non-zero exit code
+set -e 
+
 ###################################################################################
 # Print usage
 print_usage()
@@ -26,6 +25,8 @@ print_usage()
   echo "  " 
 }
 ###################################################################################
+# Initialize variables
+E_ERR=2
 if test $# -ne 1 
 then print_usage
 exit 1
@@ -43,6 +44,7 @@ if [ $SCRATCH_DIR -a $USER ]; then
     rm -rf $SCRATCH_DIR/$USER/$1
 else
     echo "Error - \$SCRATCH_DIR or \$USER environment variable not defined"
+    exit $E_ERR
 fi
 
 exit 0
diff --git a/aved-mbarivision/src/main/scripts/clip2ppm b/aved-mbarivision/src/main/scripts/clip2ppm
--- a/aved-mbarivision/src/main/scripts/clip2ppm
+++ b/aved-mbarivision/src/main/scripts/clip2ppm
@@ -1,14 +1,15 @@
 #!/bin/bash
-#set -x
-# Copyright (c) MBARI 2007
-# Author: D. Cline
-# Date: April 28, 2007 - Created
 #
-#exit on error; this will exit this bash script when any command exists with
-#a non-zero exit code
+# Name: clip2ppm
+# This script converts a video clip into individual ppm frames in preparation
+# for AVEDac processing.
+#
+# Copyright (c) MBARI 2010
+# Author: D. Cline
+#
+# exit on error - this will exit this bash script when any command exits with
+# a non-zero exit code
 set -e
-SUCCESS=0
-FAILURE=-1
 ###################################################################################
 # Print usage
 print_usage()
@@ -30,21 +31,33 @@ print_usage()
   echo "      (Example:  clip2ppm -s -t '-J smartdeinter=diffmode=2:highq=1:cubic=1,xsharpen=strength=25' -i filename.AVI -o mytest/output )"
   echo "  "
   echo -e "\033[1m -b \033[0m"
-  echo "     beginning frame. This is generally used with the ending frame option '-e'. For example
-  echo "     to transcode only the first 30 frames. However, this can also be used without the '-e' option.
+  echo "     beginning frame. This is generally used with the ending frame option '-e'. For example, "
+  echo "     to transcode only the first 30 frames:"
   echo "      (Example:  clip2ppm -b 0 -e 30 -i filename.AVI -o mytest/output )"
   echo "  "
+  echo "     However, this can also be used without the '-e' option. In this case, the ending frame defaults to the last frame of the clip."
+  echo "     For example, to transcode from the 100th frame to the end:"
+  echo "      (Example:  clip2ppm -b 100 -i filename.AVI -o mytest/output )"
+  echo "  "
   echo -e "\033[1m -e \033[0m"
-  echo "     ending frame. This is generally used with the beginning frame option '-b'. For example
-  echo "     to transcode only the first 30 frames. However, this can also be used without the '-b' option.
+  echo "     ending frame. This is generally used with the beginning frame option '-b'. "
+  echo "     For example, to transcode only the first 30 frames: " 
   echo "      (Example:  clip2ppm -b 0 -e 30 -i filename.AVI -o mytest/output )"
+  echo "  "
+  echo "     However, this can also be used without the '-b' option. In this case, the beginning frame defaults to 0."
+  echo "     For example, to transcode from the beginning to the 100th frame:"
+  echo "      (Example:  clip2ppm -e 100 -i filename.AVI -o mytest/output )"
   echo "  "
   echo "  "
 }
 frame_number=0
+
 ##################################################################################
-isdigit ()    # Tests whether *entire string* is numerical.
-{             # In other words, tests for integer variable.
+# Tests whether *entire string* is numerical.  In other words, tests for integer variable.
+# returns $SUCCESS if a numerical string; $FAILURE otherwise
+##################################################################################
+isdigit ()    
+{            
   [ $# -eq 1 ] || return $FAILURE
 
   case $1 in
@@ -102,6 +115,8 @@ timecode2counter()
     esac
 }
 ###################################################################################
+# Utility function to remove very long listings of files 
+###################################################################################
 rmall()
 {
    tmp=./tmp.$RANDOM
@@ -112,9 +127,11 @@ rmall()
 }
 ###################################################################################
 # Initialize variables
-input=0
-output=0
-use_condor_scratch=0
+E_ERR=2
+SUCCESS=0
+FAILURE=-1
+input=""
+output=""
 use_system_scratch=0
 has_timecode=0
 transcode_opts=""
@@ -128,7 +145,7 @@ end_frame=0
 args=`getopt -o t:i:o:e:b:s -- "$@" `
 if test $? != 0; then
     print_usage
-    exit
+    exit $E_ERR
 fi
 
 eval set -- "$args" 
@@ -148,9 +165,11 @@ do
   esac
 done
 
-if [ $input = 0 -o $output = 0 ]
-then print_usage
-exit 1
+
+# If the input and output files are empty print usage and exit
+if [ ! -n "$input" ] || [ !  -n "$output" ]; then
+    print_usage
+    exit $E_ERR
 fi
 
 # Add the path to the aved binaries if AVED_BIN is set
@@ -169,8 +188,8 @@ if [ $use_system_scratch = 1 ]; then
     if [ $SCRATCH_DIR -a $USER ]; then
 	outputdir=$SCRATCH_DIR/$USER/$output
     else
-	echo "Error \$SCRATCH_DIR or \$USER environment variable not defined and -s option chosen in clip2ppm script"
-	exit 1
+	echo "Error \$SCRATCH_DIR and \$USER environment variable must be defined when using the -s option"
+	exit $E_ERR
     fi
 else  
     outputdir=$output
@@ -206,7 +225,7 @@ pushd $outputdir
 # Initialize the file seed
 outputfileseed=f
 
-# Remove any files the file seed and extension
+# Remove any previous ppm files generated
 rmall "$outputfileseed*.ppm"
 
 # Check if this file has a ISO8601 timecode timestamp and extract
@@ -219,7 +238,7 @@ then
     has_timecode=1
 fi
 
-
+# Format the transcode option for start/end frames if defined
 if [ $start_frame -lt $end_frame ]; then
   transcode_opts=" -c $start_frame-$end_frame $transcode_opts "
 fi
@@ -251,7 +270,8 @@ case $input in
     echo "Executing $cmd"
     $cmd
     ;;
-    *.mov )  delimx="x"
+    *.mov )  
+    delimx="x"
     tmp=./tmp.$RANDOM
     if which oqtinfo &>/dev/null; then
 	oqtinfo -l $input > $tmp
@@ -294,6 +314,15 @@ case $input in
     cmd="transcode -q 0  -i $input -x mpeg2,null -y ppm,null -o $outputfileseed $extra_args $transcode_opts"
     echo "Executing $cmd"
     $cmd;;
+    *.wmv )
+    echo "Error unsupported format: wmv. Try using ffmpeg to convert to an avi first, for example" 
+    echo ""
+    echo "   fmpeg -i $input -r 29.97 -b 2799k -an -vtag DX50 -y $filestem.avi"
+    echo ""
+    echo "followed with:"
+    echo ""
+    echo "   clip2ppm -i $filestem.avi -o $output"
+    exit $E_ERR;; 
     * ) 
     cmd="transcode -q 0 -i $input -o $outputfileseed -y ppm,null $extra_args $transcode_opts" 
     echo "Executing $cmd"
diff --git a/aved-mbarivision/src/main/scripts/frames2mpeg b/aved-mbarivision/src/main/scripts/frames2mpeg
--- a/aved-mbarivision/src/main/scripts/frames2mpeg
+++ b/aved-mbarivision/src/main/scripts/frames2mpeg
@@ -1,17 +1,15 @@
 #!/bin/bash
-#set -x
+#
 # Name: frames2mpeg
 # This script creates an MPEG-1 from sequence of pnm,ppm,or jpg frames
 #  
 # Usage:  frames2mpeg -i [input frames directory] -o [outfilename] [OPTIONS] 
 #
-# Copyright (c) MBARI 2003
-# Author: Danelle Cline, Karen A. Salamy
-# Date: July 11, 2003
+# Copyright (c) MBARI 2010
+# Authors: Danelle Cline, Karen A. Salamy
 #
-# In part, based on runavi script written by Karen Salamy.
-# modified to run mpeg_encode after running through transcode
-# software
+# exit on error - this will exit this bash script when any command exits with
+# a non-zero exit code
 set -e 
 ###################################################################################
 # Print usage
@@ -42,22 +40,24 @@ print_usage()
   echo "  "
   echo -e "\033[1m -m [input source metadata] \033[0m"
   echo "     input video source information is defined in the file input_source_metadata.xml"
-  echo "      (Example:  runmbarivision -i  testclip/20040513T001230 -o 20040513T001230.mpeg -m 20040513T001230.metadata.xml )"
+  echo "      (Example:  frames2mpeg -i  testclip/20040513T001230 -o 20040513T001230.mpeg -m 20040513T001230.metadata.xml )"
   echo "  "
   echo -e "\033[1m -r [output framerate] \033[0m"
   echo "      video frame rate to encode in the output mpeg-r 29.97. If not defined, defaults 29.97"
   echo "      can alternatively set the video frame rate using the metadata xml from the source these" 
   echo "      frames were extracted from (see the -m option) "
-  echo "      (Example:  runmbarivision -i  testclip/20040513T001230 -r 29.97 -o 20040513T001230.mpeg -m 20040513T001230.metadata.xml )"
+  echo "      (Example:  frames2mpeg -i  testclip/20040513T001230 -r 29.97 -o 20040513T001230.mpeg -m 20040513T001230.metadata.xml )"
   echo "  "
   echo -e "\033[1m -c \033[0m"
   echo "      Specify starting and ending frames to create mpeg from. "
   echo "  "
-  echo "       runmbarivision -c 0-30 -i 20040513T001230" 
+  echo "       frames2mpeg -c 0-30 -i 20040513T001230" 
   echo "(Example:  frames2mpeg -i  testclip/20040513T001230 -c 0-10 -o 20040513T001230.mpeg)"
   echo "  "
 }
 ###################################################################################
+# Initialize variables
+E_ERR=2
 input=""
 output=""
 user=`whoami`
@@ -68,6 +68,7 @@ frame_rate=29.97
 scratch=""
 startframe=0
 endframe=0
+export HOST=`hostname`
 
 # Check arguments
 while getopts i:o:f:r:m:c:sp option
@@ -79,7 +80,7 @@ do
    r)  frame_rate="$OPTARG";;
    m)  if [ ! -f "$OPTARG" ]; then
           echo "Error - cannot find file $OPTARG"
-	  exit 1
+	  exit $E_ERR
        fi
        frame_rate=`perl -S -w extract_source_framerate.pl -i=$OPTARG`;;
    s)  use_system_scratch=1;;
@@ -96,7 +97,7 @@ done
 # If the input and output files are empty print usage and exit
 if [ ! -n "$input" ] || [ !  -n "$output" ]; then
     print_usage
-    exit 1
+    exit $E_ERR
 fi
 
 # Add the path to the aved binaries if AVED_BIN is set
@@ -115,8 +116,8 @@ if [ $use_system_scratch = 1 ]; then
 	scratch=$SCRATCH_DIR
   	inputdir=$SCRATCH_DIR/$USER/$input
     else
-	echo "Error - \$SCRATCH_DIR environment variable is not defined"
-	exit 1
+	echo "Error \$SCRATCH_DIR and \$USER environment variable must be defined when using the -s option"
+	exit $E_ERR
     fi
 else
 # Get the current frames directory, excluding the symbolic link. This is 
@@ -130,7 +131,7 @@ if [ -d $inputdir ]; then
     echo "Found $inputdir"
 else
     echo "$inputdir does not exist"
-    exit 1
+    exit $E_ERR
 fi 
 
 # If the file seed is not specified, format the outputfilestem as the base input name followed by _
@@ -188,7 +189,7 @@ echo "startframe: $startframe endframe:$endframe filestem:$filestem fileext:$inp
 # Check if the first file exists
 if [ ! -f $filestem$startframe.$input_file_ext ]; then
     echo "Error - cannot find $filestem$startframe.$input_file_ext. Specify correct file stem using -f option"
-    exit 1
+    exit $E_ERR
 fi
 
 # Get image wxh size
@@ -235,7 +236,7 @@ node7 $user /home/aved/bin/mpeg_encode
 node8 $user /home/aved/bin/mpeg_encode 
 END_PARALLEL
 PARALLEL_PERFECT
-RSH rsh 
+RSH ssh 
 _ACEOF
 # Run mpeg_encode
 cmd="mpeg_encode -debug_machines -max_machines 8 $mpegparm_file"
diff --git a/aved-mbarivision/src/main/scripts/install b/aved-mbarivision/src/main/scripts/install
--- a/aved-mbarivision/src/main/scripts/install
+++ b/aved-mbarivision/src/main/scripts/install
@@ -1,7 +1,26 @@
 #!/bin/bash
-#This script assumes you have installed mbarivision to /usr/local/aved/bin
-#If it is installed somewhere else, then change this script accordingly
-#or change your aved.sh/aved.csh.
+#
+# Name: install
+#
+# *Important* run this in the same directory as the scripts
+#
+# USAGE:  install
+#
+# This script installs the AVEDac user enviroment on
+# a single host. To setup the  environment on a Beowulf
+# cluster, run the installbeo script instead.
+#
+# This assumes mbarivision is installed in /usr/local/aved/bin
+#
+# Change this script accordingly, if it is installed in
+# another location, e.g. /usr/aved/bin, /opt/aved
+#
+# Copyright (c) MBARI 2010
+# Author: D. Cline
+#
+# exit on error - this will exit this bash script when
+# any command exits with a non-zero exit code
+set -e
  
 USERID=`id -u`
 if [ $USERID != 0 ]; then
@@ -9,11 +28,16 @@ if [ $USERID != 0 ]; then
 	exit 0
 fi
 
+if [ ! $AVED_BIN ]; then
+    echo "Error \$AVED_BIN environment variable not defined"
+    exit 1
+fi
+
 mkdir -p /usr/local/aved/scripts
 mkdir -p /usr/local/aved/bin
 cp -fp * /usr/local/aved/scripts
 
-# If a profile.d directory exists, install paths there 
+# Install paths in profile.d directory if it exists
 if [ -d /etc/profile.d ]; then 
 cat >/etc/profile.d/aved.sh <<_ACEOF 
 export AVED_BIN=/usr/local/aved/bin
@@ -26,7 +50,7 @@ setenv PATH=$PATH:/usr/local/aved/scripts:$AVED_BIN
 _ACEOF
 fi
 
-# If a profile file exists, install paths there
+# Install paths in profile file if it exists
 if [ -e /etc/profile ]; then
 cat >>/etc/profile <<_ACEOF
 export AVED_BIN=/usr/local/aved/bin
diff --git a/aved-mbarivision/src/main/scripts/installbeo b/aved-mbarivision/src/main/scripts/installbeo
--- a/aved-mbarivision/src/main/scripts/installbeo
+++ b/aved-mbarivision/src/main/scripts/installbeo
@@ -1,15 +1,20 @@
 #!/bin/bash
 #
-# set -x
 # Name: installbeo
-# This script configures the beowulf for AVED parallel processing
-# Copyright (c) MBARI 2007
+#
+# This script configures the beowulf for parallel processing with
+# pmbarivision and pvisionTCPmbari.
+# 
+# Password-less ssh login is also required for running these binaries
+# with the MPI libraries
+#
+# Copyright (c) MBARI 2010
 # Author: D. Cline
-# Date: July 10, 2007
 #
-#
-#######################################################################################
-# Defines the pmbarivision file with machine names and port ranges for MPI execution
+# exit on error - this will exit this bash script when any command exits with
+# a non-zero exit code
+set -e
+
 # Check if root
 USERID=`id -u`
 if [ $USERID != 0 ]; then
@@ -30,7 +35,7 @@ cat >$file <<_ACEOF
 #######################################################################
 # Configuration file for AVED parallel version
 #######################################################################
-# Defines the ports to use for the parallel mbarivision
+# Defines the ports to use for the pmbarivision
 # The PMBARIVISION_PORT_START/END must be a different
 # range than the PVISIONWORKER_PORT_START/END
 #######################################################################
@@ -38,25 +43,20 @@ PMBARIVISION_PORT_START=$pmbarivis_portstart
 PMBARIVISION_PORT_END=$pmbarivis_portend
 
 #######################################################################
-# Defines the ports to use for the pvision workers
+# Defines the ports to use for the pvisionTCPmbari workers
 #######################################################################
 PVISIONWORKER_PORT_START=$pvisworker_portstart
 PVISIONWORKER_PORT_END=$pvisworker_portend
 _ACEOF
 
-# Create if needed and move into the installation directory
-if [ ! -d /etc/aved ]; then
-    mkdir /etc/aved
-fi
+# Create install directory and move into it
+mkdir -p /etc/aved
 pushd /etc/aved;
 
 # Move out of the installation directory
 popd;
 
-# Calculate port range overlap. I'm sure there is a more elegant way to do this, but this works fine
-overlap=`seq $pvisworker_portstart $pvisworker_portend | grep "9800\|9760"`
-
-# Test for correct port ranges and if there is an overlap in ports
+# Test for correct port definitions
 if [ $pvisworker_portstart -ge $pvisworker_portend ]; then
     echo "Invalid range for PVISIONWORKER_PORT_START $pmbarivis_portstart and PVISIONWORKER_PORT_END $pmbarivis_portend"
     exit 1
@@ -67,6 +67,10 @@ if [ $pmbarivis_portstart -ge $pmbarivis_portend ]; then
     exit 1
 fi
 
+# Calculate port range overlap between vision workers and pmbarivision
+# I'm sure there is a more elegant way to do this, but this works fine
+overlap=`seq $pvisworker_portstart $pvisworker_portend | grep "9800\|9760"`
+
 if [ "$overlap" != "" ]; then 
     echo "Error PMBARIVISION_PORT_START/END ranges must not overlap with PVISIONWORKER_PORT_START/END"
     echo "Port ranges overlap at: "
@@ -76,9 +80,5 @@ fi
 
 # Copy the configuration to all the cluster nodes
 cpush /etc/aved/  
-
-# Copy the mpich configuration to the machines files
-# Set this to the correct directory of your MPICH2 installation
-cpush /opt/mpich2-1.0/etc/mpd.hosts 
 
 exit 0
diff --git a/aved-mbarivision/src/main/scripts/mp2script b/aved-mbarivision/src/main/scripts/mp2script
--- a/aved-mbarivision/src/main/scripts/mp2script
+++ b/aved-mbarivision/src/main/scripts/mp2script
@@ -1,20 +1,14 @@
 #!/bin/bash
-# set -x
+#
 # Name: mp2script
 # This script is to be used with Condor
 # to launch an MPICH2 executable with the mpirun command
 #
-# The number of processes and condor parallel universe logic
-# can be overriden in this with the -n and -c options respectively
-# These are used in AVED processing to allow execution of
-# more than on MPI process on a given node.
-#
+# Copyright (c) MBARI 2010
 # Author: D. Cline
-# Date: July 09, 2007
 #
-###################################################################################
-# Exit on error; thie will exit this script when any command exist with a non-zero
-# exit code
+# exit on error - this will exit this bash script when any command exits with
+# a non-zero exit code
 set -e
 #############################################################
 rundbg()
@@ -35,6 +29,7 @@ $1
 }
 #############################################################
 # Initialize defaults
+E_ERR=1
 skip_condor_proc=0
 debug=0
 job_alias=$USER
@@ -44,7 +39,7 @@ final_args=
 MPDIR=/opt/mpich2-1.1p1
 PATH=$MPDIR/bin:.:$PATH
 export PATH
-machine_file=
+machine_file=""
 
 # Check arguments
 while getopts a:h:e:g:n:cd option 
@@ -66,6 +61,8 @@ if [ ! "$machine_file" ]; then
     echo "Error -no machine file specified" 
 fi
 
+_condor_procno=0
+
 # Used when running with Condor, but not for debugging
 if [ $skip_condor_proc -eq 0 ] ;then
     _condor_procno=$_condor_procno
@@ -79,35 +76,45 @@ if [ $skip_condor_proc -eq 0 ] ;then
 fi
 
 
-# Start the mpich2 environment
+# Setup the mpich2 environment
 export LD_LIBRARY_PATH=/lib:/usr/lib:/home/aved/lib:$MPDIR/lib
-export P4_RSHCOMMAND=/usr/bin/rsh
+export P4_RSHCOMMAND=/usr/bin/ssh
 
 if [ ! -f $machine_file ]; then
     echo "Machine file '$machine_file' invalid or missing "
-    exit 1
+    exit $E_ERR
 fi
 
-# The first field in the contact file is the machine name
-# that condor_ssh knows how to use
-echo "----MPI machines in $machine_file ------------"
+# The machines to use in this job
+echo "----MPI machines used in job alias $job_alias ------------"
 sort -n +0 < $machine_file | awk '{print $1}' 
-echo "----MPI machines------------"
 
 # Override the number of processes if requested
 if [ $override_nprocs ]; then
     _condor_nprocs=$override_nprocs
 fi   
 
-# MPICH2 requires an mpd.conf file with a password in it on the host starting the job.
+# MPICH2 requires an mpd.conf file with a password in it 
+# in the users home directory on the host starting the job.
 export MPD_CONF_FILE=$HOME/.mpd.conf
 echo "MPD_SECRETWORD=nanomia" > $MPD_CONF_FILE
-echo "MPD_USE_ROOT_MPD=yes" >> $MPD_CONF_FILE
 chmod 600 $MPD_CONF_FILE
 
-echo "----MPI trace------------"
-mpdtrace
-echo "----MPI trace------------"
+# Start the MPD ring if there isn't one already started
+# This assumes the system-wide mpd.host file is readable by all users
+numhosts=`wc -l $MPDIR/etc/mpd.hosts | awk '{print $1}'`
+numhostsup=`mpdtrace | wc -l`
+
+if [ $numhosts -eq $numhostsup ]; then 
+    echo "mpd already running for user $USER"
+else
+    cmd="mpdboot --rsh=$P4_RSHCOMMAND --file=$MPDIR/etc/mpd.hosts --totalnum=$numhosts --mpd=$MPDIR/bin/mpd.py"
+    echo "Executing $cmd"
+    $cmd
+fi
+
+# To avoid leaving the mpi job hanging trap ctrl-c or terminate signals and kill the job gracefully
+trap 'echo "mp2script job alias $job_alias was interrupted"; mpdkilljob -a $job_alias; echo;exit $E_ERR' INT TERM EXIT
 
 # If not debugging, run the MPI job
 if [ $debug -eq 0  ] ;then
@@ -118,9 +125,9 @@ else
     echo "Executing mpigdb -n $_condor_nprocs -l -m -s $executable" "$executable" "$final_args"
     rundbg "mpigdb -machinefile $machine_file -n $_condor_nprocs -machinefile $machinefile -l -m -s $executable" "$executable" "$final_args" ;
 fi
+trap - INT TERM EXIT
 
 rc=$?
-rm $MPD_CONF_FILE
 
 echo "----------------->mp2script done - return code $rc !!<--------------------------"	 
 exit $rc
diff --git a/aved-mbarivision/src/main/scripts/runpmbarivision b/aved-mbarivision/src/main/scripts/runpmbarivision
--- a/aved-mbarivision/src/main/scripts/runpmbarivision
+++ b/aved-mbarivision/src/main/scripts/runpmbarivision
@@ -1,32 +1,61 @@
 #!/bin/bash
-# set -x
-# Name: runpmbarivision -w <worker_list>
+#
+# Name: runpmbarivision -w <worker_list> -a '<arguments to pass to pmbarivision>'
 #
 # This script executes the pmbarivision executable from any node in the beowulf cluster
-# using the mp2script. Workers to be used with this executable are defined in the
-# <worker_list> file
-#
-# Copyright (c) MBARI 2007
+# using the mp2script. pvisionTCPmbari workers to be used with this executable are 
+# defined in the <worker_list> file
+# 
+# Copyright (c) MBARI 2010
 # Author: D. Cline
-# Date: November 28, 2007
-#######################################################################################
-#exit on error; this will exit this bash script when any command exists with
-#a non-zero exit code
-#set -e
 #######################################################################################
 # init default variables
-E_NOFILE=66
+E_ERR=2
+E_NOPORTS=3
 debug=0 #debugging flag set to 1 to debug the pmbarivision binary
-worker_list=0
+worker_list=""
 num_procs=5 #only need 5 nodes for the pmbarivision MPI executable
-args=0
+args=""
 ############################################################################
 # Print usage
 print_usage()
 {
   echo "  "
-  echo -e "USAGE: runpmbarivision -w [worker output list -a "arguments to pass to pmbarivision" ]"
+  echo -e "USAGE: runpmbarivision -w workerfile  -a 'arguments to pass to pmbarivision' "
   echo "  "
+  echo -e "\033[1m -w \033[0m"
+  echo "      worker file containing the list of workers running pvisionTCPmbari "
+  echo "      that runpmbarivision will contact to execute the saliency computation"
+  echo "  "
+  echo "      this file must be formatted in the format:   node:port, e.g."
+  echo "  "
+  echo "      master.private.net:9726,node6.private.net:9726,node7.private.net:9726,"
+  echo "      node4.private.net:9726,node2.private.net:9726,node1.private.net:9726,"
+  echo "      node3.private.net:9726 "
+  echo "  "
+  echo -e "\033[1m -a \033[0m"
+  echo "      pass arguments to the pmbarivision executable. Be sure to enclose the "
+  echo "      arguments in quotes." 
+}
+###################################################################################
+# Beginning of runpmbarivision script
+###################################################################################
+checkexe()
+{
+# Find the executable 
+exe="`type -p $1`" 
+
+# If not found then we cannot use this script so bail out now
+if [ ! $exe ]; then
+   echo "Error: $1 not found"
+   exit 1
+fi
+
+# Change permissions if not set correctly by Condor transfer 
+if [ ! -x $exe ]; then
+   echo "Changing $exe to executable by user"
+   chmod u+x $exe
+fi
 }
 ############################################################################
 # Get port number
@@ -42,7 +71,7 @@ for i in `seq 1 10`
   do
   if ( set -o noclobber; echo "$$" > "$lockfile" ) 2>/dev/null;
       then
-      trap 'rm -f "$lockfile"; exit $?' INT TERM EXIT
+      trap 'rm -f "$lockfile"; exit $?' INT TERM 
      
       nextavail_port=`cat $portfile`
 
@@ -107,10 +136,10 @@ machine_file=`pwd`/pmbarivisionmachines
 
 if [ ! -f $host_file ]; then
     echo "File \"$host_file\" does not exist"
-    exit $E_NOFILE
+    exit $E_ERR
 fi
 
-# Only need 5 of the nodes for this 
+# Get the first $num_proces and put into  the machine file 
 head -n $num_procs $host_file > $machine_file
 
 # Check arguments
@@ -123,60 +152,73 @@ do
   esac
 done
 
-shift $((OPTIND-1))
-
-if [ [ $worker_list = 0  ] || [ $args = 0 ] ]
-then print_usage
-exit 1
+# If the worker list is missing then print usage and exit
+if [ ! -n "$worker_list"  ]; then
+    print_usage
+    exit $E_ERR
 fi
-
-# Defines the pvision workers - these are the workers that compute saliency
-# retry 10 times, and wait 3 second between retries in case the workers
-# are not running yet
-for i in `seq 1 10`
-  do
-  if [ ! -f $worker_list ]; then
-      echo "File \"$worker_list\" does not exist"
-      if [ "$i" = 4 ]; then 
-	  exit $E_NOFILE
-      fi
-  else
-      # Check if the mpi process is running
-      workerlist=`cat $worker_list`
-      pvisport=`cat $worker_list | cut -f2 -d ":" | cut -f1 -d ","`
-      tmp=`mpdlistjobs | grep pvisionTCPmbari$pvisport`
-      if [ "$tmp" == "" -a "$i" = 4 ]; then
-	  echo "Error - pvisionTCPmbari on $pvisport not running !!!"
-	  exit $E_NOFILE
-      else
-	  break
-      fi
-  fi
-  echo "Sleeping 3 seconds"
-  sleep 3
-done
-
-echo "Found $worker_list"
 
 # Define the MPI executable
-if [ $AVED_BIN ]; then
-    exec_file=$AVED_BIN/pmbarivision
+if [ ! $AVED_BIN ]; then
+    echo "Error - AVED_BIN environment variable not defined"
+    exit $E_ERR
 else
-    echo "Error - "$AVED_BIN" environment variable not defined"
-    exit 1
+    exec_file=$AVED_BIN/pmbarivision
 fi
 
-if [ ! $SCRATCH_DIR ]; then
-    echo "Error - "$SCRATCH_DIR" environment variable not defined"
-    exit 1
-fi
-
-# Define the MPI setup file and extract the port ranges for the pvisionmachine
+# Define the MPI setup file 
 mpisetup=/etc/aved/pmbarivision.mpi
 if [ ! -f $mpisetup ]; then
     echo "File \"$mpisetup\" does not exist"
-    exit $E_NOFILE
+    exit $E_ERR
 fi
+
+if [ ! $SCRATCH_DIR ]; then
+    echo "Error - SCRATCH_DIR environment variable not defined"
+    exit $E_ERR
+fi
+
+# Make sure runpvisionworkers is executable
+checkexe runpvisionworkers
+
+# Start up the pvision workers
+echo "Running runpvisionworkers -w "$worker_list""
+runpvisionworkers -w "$worker_list" & 
+pvis_pid=$!
+trap 'kill -9 $pvis_pid; exit $?' INT TERM EXIT
+echo "Sleeping 3 seconds waiting for workers to start"
+sleep 3
+pvisport=""
+
+# Check if the pvision workers are running 
+# retry 3 times, and wait 5 seconds between retries in case the workers
+# are not running yet
+for i in `seq 1 3`
+  do
+  
+  if [ ! -e "$worker_list" ]; then
+	if [ "$i" = 3 ]; then
+    	  echo "Error - cannot find $worker_list; this probably means the workers have failed"
+    	  exit $E_ERR
+    	  break
+	fi
+  else 
+    workerlist=`cat $worker_list`
+    pvisport=`cat $worker_list | cut -f2 -d ":" | cut -f1 -d ","`
+    echo "Looking for pvisionTCPmbari workers on port $pvisport" 
+# Check if the mpi job is running by looking up the job alias
+  tmp=`mpdlistjobs | grep pvisionTCPmbari$pvisport`
+  if [ "$tmp" ]; then
+     echo "Found pvisionTCPmbari workers on port $pvisport"
+     break
+  elif [ "$tmp" = "" -a "$i" = 3 ]; then
+     echo "Error - pvisionTCPmbari on $pvisport not running !!!"
+     exit $E_ERR
+  fi
+fi
+      echo "Retry $i after sleeping 5 seconds"
+      sleep 5  
+done
 
 portstart=`cat $mpisetup | grep "PMBARIVISION_PORT_START=" | cut -f2 -d "="`
 portend=`cat $mpisetup | grep "PMBARIVISION_PORT_END=" | cut -f2 -d "="`
@@ -195,21 +237,20 @@ if [ ! -e $portfile ]; then
     chmod a+rwx $portfile
 fi
 
+# Get the next available port
 getportnum $portfile $portstart $portend
    
 if [ $nextavail_port -eq -1 ]; then
     echo "Error - no ports available for processing.  Please try again in a few minutes"
-    exit 1
+    exit $E_NOPORTS
 fi
  
 # Append arguments for beowulf workers and disable floating point exceptions to 
 # make this version more tolerant to exceptions
-args="$args --ip-port=$nextavail_port --beowulf-slaves=$workerlist --use-fpe=false $@"
+args="$args --ip-port=$nextavail_port --beowulf-slaves=$workerlist --use-fpe=false"
       
 # Make sure mp2script is executable
-if [ ! -x mp2script ]; then
-    chmod u+x mp2script
-fi
+checkexe mp2script
 
 # Format and run command
 # If not running in debugger, then just run
@@ -217,15 +258,17 @@ if [ $debug = 0 ]; then
     echo "Running mp2script -h $machine_file -a pmbarivision$USER$nextavail_port -n $num_procs -e $exec_file -g "$args""
     mp2script -h $machine_file -a pmbarivision$USER$nextavail_port -n $num_procs -e $exec_file -g "$args"
 else
-    echo "Running mp2script -h $machine_file -a pmbarivision$USER$nextavail_port -n 5 -e $exec_file -g "$args""
-    mp2script -d -h $machine_file -a pmbarivision$USER$nextavail_port -n $num_procs -e $exec_file -g "$args" 
+    echo "Running mp2script -h $machine_file -a pmbarivision$USER$nextavail_port -n $num_procs -e $exec_file -g "$args""
+    mp2script -d -h $machine_file -a pmbarivision$USER$nextavail_port -n $num_procs -e $exec_file -g "$args"
 fi 
 
-# Kill pvisionworkers to free them up for someone else to use
+rc=$?
+trap - INT TERM EXIT
+
+# Kill pvisionTCPmbari workers in case they are still running 
 echo "Running  mpdkilljob -a pvisionTCPmbari$pvisport"
-mpdkilljob -a pvisionTCPmbari$pvisport 	
-rm -f $worker_list
+mpdkilljob -a pvisionTCPmbari$pvisport 
 
 echo "----------------------->runpmbarivision done - exit code: $? !!<-------------------"
-exit $?
+exit $rc
 
diff --git a/aved-mbarivision/src/main/scripts/runpvisionworkers b/aved-mbarivision/src/main/scripts/runpvisionworkers
--- a/aved-mbarivision/src/main/scripts/runpvisionworkers
+++ b/aved-mbarivision/src/main/scripts/runpvisionworkers
@@ -1,5 +1,5 @@
 #!/bin/bash
-# set -x
+#
 # Name: runpvisionworkers -w <worker_list>
 #
 # This script executes the mp2script to launch the pvisionTCPmbari workers
@@ -10,19 +10,21 @@
 # systerm on the Beowulf cluster, such as /mnt/scratch.
 # 
 # This is intended to be used in conjunction with the runpmbarivision
-# script. Pass the same <worker_list> to the runpmbarivision 
+# bash script. Pass the same <worker_list> to the runpmbarivision 
 # <worker_list> executable
 # 
-# Copyright (c) MBARI 2007
+# Copyright (c) MBARI 2010
 # Author: D. Cline
-# Date: July 09, 2007
+#
 ############################################################################
+set -e
 # Init default variables
-E_NOFILE=66
+E_ERR=2
+E_NOPORTS=3
 SUCCESS=0
 FAILURE=-1
 debug=0 #debugging flag set to 1 to debug the pvisionTCPmbari binary
-worker_list=
+worker_list=""
 randomize_perl_script=randomize.pl
 num_pvis_workers=7
 port=-1
@@ -34,6 +36,26 @@ print_usage()
   echo -e "USAGE: runpvisionworkers -w [worker output list]"
   echo "  "
 }
+###################################################################################
+# Beginning of runpmbarivision script
+###################################################################################
+checkexe()
+{
+# Find the executable 
+exe="`type -p $1`"
+
+# If not found then we cannot use this script so bail out now
+if [ ! $exe ]; then
+   echo "Error: $1 not found"
+   exit 1
+fi
+
+# Change permissions if not set correctly by Condor transfer 
+if [ ! -x $exe ]; then
+   echo "Changing $exe to executable by user"
+   chmod u+x $exe
+fi
+}
 ############################################################################
 # Get port number
 getportnum()
@@ -43,13 +65,11 @@ lockfile=$1\.lock
 portstart=$2
 portend=$3
 nextavail_port=-1
-
 for i in `seq 1 10`
   do
   if ( set -o noclobber; echo "$$" > "$lockfile" ) 2>/dev/null;
       then
-      trap 'rm -f "$lockfile"; exit $?' INT TERM EXIT
-     
+      trap 'rm -f "$lockfile"; echo "runpvisionworkers TRAP"; exit $E_ERR' INT TERM EXIT 
       nextavail_port=`cat $portfile`
 
       # If port is out of range, then reset it
@@ -63,8 +83,19 @@ for i in `seq 1 10`
       for port in `seq $nextavail_port $portend`
 	do
         # Gather information about any jobs or processes potentially using this port
-	mpdjobs=`mpdlistjobs | grep $port`
-	netstatlocal=`netstat | grep '$port' | grep TIME_WAIT `
+	if [ `mpdcheck` ]; then
+   	jobs=`mpdlistjobs`
+	else
+	jobs=""
+	fi
+	if [ "$jobs" -a "$port" ]; then
+	mpdjobs=`echo $jobs | grep $port`
+	else
+	mpdjobs=""
+	fi
+	if [ "`netstat -t | grep "$port" | grep TIME_WAIT `" ]; then
+	netstatlocal=`netstat -t | grep "$port" | grep TIME_WAIT `
+	fi
 	pvisionjobs=`ps -eo "%p %a" | grep -e pvisionTCPmbari | grep -e $port | cut -f1 -s -d " "`  	  
 	
         # If port is being used by another job report it
@@ -85,12 +116,14 @@ for i in `seq 1 10`
         # Increment and write the next available port
 	    ((port += 1))
 	    echo "$port" > $portfile  
+            rm -f "$lockfile"
+            trap - INT TERM EXIT 
 	    break
 	fi
       done
 
       rm -f "$lockfile"
-      trap - INT TERM EXIT
+      trap - INT TERM EXIT 
       break
   else
       echo "Failed to acquire lockfile: $lockfile."
@@ -119,28 +152,35 @@ do
   esac
 done
 
-shift $((OPTIND-1))
-
-if [ "x$worker_list" = x  ]; then 
-print_usage
-exit 1
+# If the worker list is not defined print usage and exit
+if [ ! "$worker_list"  ]; then
+    print_usage
+    exit $E_ERR
 fi
 
 # Setup MPI 
 MPDIR=/opt/mpich2-1.1p1/bin
 export PATH=$MPDIR:.:$PATH
 
+# Check all the required environment variables
+if [ ! $SCRATCH_DIR ]; then
+    echo "Error \$SCRATCH_DIR not defined. Set this to the directory"
+    exit $E_ERR
+fi
+
+if [ ! $AVED_BIN ]; then
+    echo "Error \$AVED_BIN environment variable not defined. Set this to the directory pvisionTCPmbari executable is in."
+    exit $E_ERR
+fi
+
+# Add the condor scratch path to the path for running
+# executables
 if [ $_CONDOR_SCRATCH_DIR ]; then
     export PATH=$_CONDOR_SCRATCH_DIR:$PATH
 fi
 
 # Define the pvisionTCP executable
-if [ $AVED_BIN ]; then
-    exec_file=$AVED_BIN/pvisionTCPmbari
-else
-    echo "Error - "\$AVED_BIN" environment variable not defined. Define this to the location that the mbarivision/pmbarivision executables reside in."
-    exit 1
-fi
+exec_file=$AVED_BIN/pvisionTCPmbari
 
 # Define the machine file. Change this to point to the MPICH installation 
 # directory on your machine
@@ -149,7 +189,7 @@ machine_file=$MPDIR/etc/mpd.hosts
 
 if [ ! -f $machine_file ]; then
     echo "File \"$machine_file\" does not exist"
-    exit $E_NOFILE
+    exit $E_ERR
 fi
 
 echo "----MPI machines available------------"
@@ -159,16 +199,15 @@ sort -n +0 < $machine_file | awk '{print $1}'
 mpisetup=/etc/aved/pmbarivision.mpi
 if [ ! -f $mpisetup ]; then
     echo "File \"$mpisetup\" does not exist"
-    exit $E_NOFILE
+    exit $E_ERR
 fi
-
 # Extract the port ranges for the workers and check if they are valid digits
 portstart=`cat $mpisetup | grep "PVISIONWORKER_PORT_START=" | cut -f2 -d "="`
 portend=`cat $mpisetup | grep "PVISIONWORKER_PORT_END=" | cut -f2 -d "="`
 
 if ! isdigit "$portstart" || !  isdigit "$portend" ; then
     echo "Invalid ports defined: $portstart $portend correct this in the file: $mpisetup "
-    exit 2
+    exit $E_ERR
 fi
 
 # Define the port file that maintains the last used port
@@ -190,17 +229,12 @@ getportnum $portfile $portstart $portend
    
 if [ $nextavail_port -eq -1 ]; then
     echo "Error - all workers busy. No vision workers available for processing.  Please try again in a few minutes"
-    exit 1
+    exit $E_NOPORTS
 fi
 
 # Export the contact file for CONDOR to use
 CONDOR_CONTACT_FILE="`pwd`"\/pvisionworkermachines
 
-if [ ! -x $randomize_perl_script ]; then
-    echo "Changing permissions on $randomize_perl_script"
-    chmod u+x $randomize_perl_script
-fi
- 
 # Remove the first line of the machine file listing and preserve this from the randomize
 # *IMPORTANT* THIS ASSUMES THE FIRST LINE IN YOUR mpd.hosts file is the master node in your 
 # Beowulf cluster from where this script will be run
@@ -210,40 +244,41 @@ sed '1d' $machine_file > mpd.conf
 # heavy loading on particular machines because some workers do more work than others
 perl -S $randomize_perl_script mpd.conf > mpd.conf.tmp  
 
-# Reinsert the first line which should be the  master node
+# Reinsert the first line which should be the master node
 a=`head -n 1 $machine_file`
 sed -i '1i\'$a'' mpd.conf.tmp
 
 # Add an extra line to work with sed in next format.
 # This allows the last item in the list to parse out correctly 
 # in the next sed function that appends the port number to each host
+
 head -n $num_pvis_workers mpd.conf.tmp > $CONDOR_CONTACT_FILE
 echo "" >> $CONDOR_CONTACT_FILE
-rm mpd.conf.tmp mpd.conf
+rm mpd.conf*
 
 # Append :port to each host in the machine file
 workers=`sed -e:a -e'$!N;s/\n/:'$nextavail_port,/';ta' -e 'P;D' $CONDOR_CONTACT_FILE `
   
-# Now remove the emtpy line
+# Now remove the empty line
 sed -i '/^$/d' $CONDOR_CONTACT_FILE
 
 # Strip off the last comma (,) and put the worker list in a file
 list=${workers/%$nextavail_port,/$nextavail_port}  
 echo $list  > $worker_list      
   
-# Make sure the mp2script is executable
-if [ ! -x mp2script ]; then
-   chmod u+x mp2script
-fi
+# Make sure the mp2script is executable 
+checkexe mp2script 
+
+args="--logverb=Error --ip-port=$nextavail_port"
  
-# If not running in debugger, then just run
+# If not running in debugger, then just run 
 if [ $debug = 0 ]; then
-    echo "Running mp2script -a pvisionTCPmbari$nextavail_port -h $CONDOR_CONTACT_FILE  -e $exec_file -n $num_pvis_workers -c -g "--logverb=Error --ip-port=$nextavail_port" "
-    mp2script -a pvisionTCPmbari$nextavail_port -h $CONDOR_CONTACT_FILE  -n $num_pvis_workers -e $exec_file -c -g "--logverb=Error --ip-port=$nextavail_port"
+    echo "Running mp2script -a pvisionTCPmbari$nextavail_port -h $CONDOR_CONTACT_FILE  -e $exec_file -n $num_pvis_workers -c -g "$args""
+    mp2script -a pvisionTCPmbari$nextavail_port -h $CONDOR_CONTACT_FILE  -n $num_pvis_workers -e $exec_file -c -g "$args"
 else
-    echo "Running mp2script -d -a pvisionTCPmbari$nextavail_port -h $CONDOR_CONTACT_FILE  -e $exec_file -n num_pvis_workers -c -g "--ip-port=$nextavail_port" "
-    mp2script -d -a pvisionTCPmbari$nextavail_port -h $CONDOR_CONTACT_FILE -n $num_pvis_workers -e $exec_file -c -g "--ip-port=$nextavail_port"
-fi
+    echo "Running mp2script -d -a pvisionTCPmbari$nextavail_port -h $CONDOR_CONTACT_FILE  -e $exec_file -n num_pvis_workers -c -g "$args""
+    mp2script -d -a pvisionTCPmbari$nextavail_port -h $CONDOR_CONTACT_FILE -n $num_pvis_workers -e $exec_file -c $args
+fi 
 rc=$?
 rm -f $worker_list
 
